name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write
  actions: read
  pull-requests: write

jobs:
  build-and-test:
    name: Build · Lint · Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter (if present)
        run: |
          if [ -f package.json ] && jq -r '.scripts.lint // empty' package.json | grep -q .; then
            npm run lint
          else
            echo "No lint script found — skipping lint."
          fi

      - name: Run tests
        run: |
          if [ -f package.json ] && jq -r '.scripts.test // empty' package.json | grep -q .; then
            npm test -- --reporter=json > test-results.json || true
          else
            echo "No test script found — skipping tests."
          fi

      - name: Upload test results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-test-results
          path: |
            test-results.json
            coverage/
            ./npm-debug.log

      - name: Display summary
        if: always()
        run: |
          echo "==== CI job completed ===="
